// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["MYSQL_DATABASE_CONNECTION_STRING"];

if (!databaseUrl) {
  throw new Error(
    "Please define the MYSQL_DATABASE_CONNECTION_STRING environment variable inside .env",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
